/run/initialize

# Open visualization system
/vis/open OGL

# Create the scene and viewer
/vis/scene/create
/vis/viewer/create
/vis/viewer/set/viewpointThetaPhi 90 90

# Attach geometry
/vis/drawVolume
/vis/scene/add/volume
/vis/scene/add/axes 0 0 0 100 nm
/vis/scene/add/trajectories smooth
/vis/scene/add/hits
/vis/sceneHandler/attach

# Color particle trajectories
/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/set gamma green
/vis/modeling/trajectories/drawByParticleID-0/set proton red
/vis/modeling/trajectories/drawByParticleID-0/set e- blue
/vis/modeling/trajectories/drawByParticleID-0/set neutron yellow
/vis/modeling/trajectories/drawByParticleID-0/set mu- magenta
/vis/modeling/trajectories/drawByParticleID-0/set mu+ cyan
/vis/modeling/trajectories/drawByParticleID-0/set muAlpha5p white

# Scene options
/vis/drawOnlyToBeKeptEvents true
/vis/scene/endOfEventAction accumulate 1000
/tracking/storeTrajectory 1
/vis/viewer/set/autoRefresh true
/vis/enable

# Beam on
/run/printProgress 1000
/run/beamOn 1000